package com.deepseek.harness4j.cordis;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Fluent builder and generator for Cordis composition YAML configurations ({@code cordis.yml}).
 */
public final class CordisConfig {

    public enum CompressionMode {
        ZSTD("zstd"),
        NONE("none");

        private final String wireName;

        CompressionMode(String wireName) {
            this.wireName = wireName;
        }

        public String wireName() {
            return wireName;
        }
    }

    private final String provider;
    private final String model;
    private final String sessionRoot;
    private final CompressionMode compression;
    private final boolean persistentBash;
    private final boolean strReplaceEditor;
    private final boolean toolFs;
    private final boolean subagent;
    private final boolean compaction;
    private final boolean tokenMeter;
    private final SandboxPolicy sandboxPolicy;
    private final String customPersona;
    private final Map<String, Object> extraPlugins;

    private CordisConfig(Builder builder) {
        this.provider = builder.provider;
        this.model = builder.model;
        this.sessionRoot = builder.sessionRoot;
        this.compression = builder.compression == null ? CompressionMode.ZSTD : builder.compression;
        this.persistentBash = builder.persistentBash;
        this.strReplaceEditor = builder.strReplaceEditor;
        this.toolFs = builder.toolFs;
        this.subagent = builder.subagent;
        this.compaction = builder.compaction;
        this.tokenMeter = builder.tokenMeter;
        this.sandboxPolicy = builder.sandboxPolicy;
        this.customPersona = builder.customPersona;
        this.extraPlugins = new LinkedHashMap<>(builder.extraPlugins);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Build the Minimal Benchmark composition (matching {@code minimal.cordis.yml}).
     */
    public static CordisConfig minimal() {
        return builder()
                .persistentBash(true)
                .strReplaceEditor(true)
                .toolFs(false)
                .subagent(false)
                .compaction(false)
                .compression(CompressionMode.NONE)
                .build();
    }

    /**
     * Generate the complete YAML configuration string.
     */
    public String toYaml() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by deepseek-harness4j CordisConfig DSL\n\n");

        // 1. SDK jsonrpc server
        sb.append("- id: sdk-jsonrpc-server\n");
        sb.append("  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'\n\n");

        // 2. LLM adapter
        sb.append("- id: llm-deepseek\n");
        sb.append("  name: '@deepseek-ai/dsh-llm-deepseek'\n");
        if (model != null) {
            sb.append("  config:\n");
            sb.append("    models:\n");
            sb.append("      - id: ").append(model).append("\n");
        }
        sb.append("\n");

        // 3. Sandbox
        sb.append("- id: sandbox\n");
        sb.append("  name: '@deepseek-ai/dsh-sandbox-local'\n\n");

        // 4. Sandbox policy
        sb.append("- id: sandbox-policy\n");
        sb.append("  name: '@deepseek-ai/dsh-sandbox-policy'\n");
        sb.append("  config:\n");
        String mode = sandboxPolicy != null ? sandboxPolicy.mode() : SandboxPolicy.MODE_DANGER_FULL_ACCESS;
        sb.append("    mode: ").append(mode).append("\n");
        sb.append("    workspaceRoot: !!js process.env.DSH_CWD ?? process.cwd()\n\n");

        // 5. Subprocess & terminal
        sb.append("- id: subprocess\n");
        sb.append("  name: '@deepseek-ai/dsh-subprocess-local'\n\n");

        // 6. FS
        sb.append("- id: fs-local\n");
        sb.append("  name: '@deepseek-ai/dsh-fs-local'\n");
        sb.append("  config:\n");
        sb.append("    cwd: !!js process.env.DSH_CWD ?? process.cwd()\n\n");

        // 7. Agent spine
        sb.append("- id: agent-spine\n");
        sb.append("  name: '@deepseek-ai/dsh-agent-spine-demo'\n");
        sb.append("  config:\n");
        if (customPersona != null) {
            sb.append("    persona: \"").append(customPersona.replace("\"", "\\\"")).append("\"\n");
        }
        if (!persistentBash && !toolFs) {
            sb.append("    workspaceContext: false\n");
        }
        sb.append("\n");

        // 8. Tools
        if (persistentBash) {
            sb.append("- id: persistent-bash\n");
            sb.append("  name: '@deepseek-ai/dsh-tool-bash-persistent'\n\n");
        }
        if (strReplaceEditor) {
            sb.append("- id: str-replace-editor\n");
            sb.append("  name: '@deepseek-ai/dsh-tool-str-replace-editor'\n\n");
        }

        // 9. Sessions persistence
        sb.append("- id: sessions\n");
        sb.append("  name: '@deepseek-ai/dsh-session-persistence-jsonl'\n");
        sb.append("  config:\n");
        if (sessionRoot != null) {
            sb.append("    root: ").append(sessionRoot).append("\n");
        } else {
            sb.append("    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'\n");
        }
        if (compression == CompressionMode.NONE) {
            sb.append("    compression: none\n");
        }
        sb.append("\n");

        return sb.toString();
    }

    /**
     * Write this configuration to a temporary {@code .cordis.yml} file that is deleted on JVM exit.
     */
    public Path toTempFile() throws IOException {
        Path temp = Files.createTempFile("deepseek-cordis-", ".cordis.yml");
        Files.writeString(temp, toYaml(), StandardCharsets.UTF_8);
        temp.toFile().deleteOnExit();
        return temp;
    }

    public static final class Builder {
        private String provider;
        private String model;
        private String sessionRoot;
        private CompressionMode compression = CompressionMode.ZSTD;
        private boolean persistentBash = true;
        private boolean strReplaceEditor = true;
        private boolean toolFs = true;
        private boolean subagent = false;
        private boolean compaction = false;
        private boolean tokenMeter = true;
        private SandboxPolicy sandboxPolicy;
        private String customPersona;
        private final Map<String, Object> extraPlugins = new LinkedHashMap<>();

        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }

        public Builder model(String model) {
            this.model = model;
            return this;
        }

        public Builder sessionRoot(String sessionRoot) {
            this.sessionRoot = sessionRoot;
            return this;
        }

        public Builder compression(CompressionMode compression) {
            this.compression = compression;
            return this;
        }

        public Builder persistentBash(boolean persistentBash) {
            this.persistentBash = persistentBash;
            return this;
        }

        public Builder strReplaceEditor(boolean strReplaceEditor) {
            this.strReplaceEditor = strReplaceEditor;
            return this;
        }

        public Builder toolFs(boolean toolFs) {
            this.toolFs = toolFs;
            return this;
        }

        public Builder subagent(boolean subagent) {
            this.subagent = subagent;
            return this;
        }

        public Builder compaction(boolean compaction) {
            this.compaction = compaction;
            return this;
        }

        public Builder tokenMeter(boolean tokenMeter) {
            this.tokenMeter = tokenMeter;
            return this;
        }

        public Builder sandboxPolicy(SandboxPolicy sandboxPolicy) {
            this.sandboxPolicy = sandboxPolicy;
            return this;
        }

        public Builder customPersona(String customPersona) {
            this.customPersona = customPersona;
            return this;
        }

        public Builder addExtraPlugin(String id, Object config) {
            this.extraPlugins.put(id, config);
            return this;
        }

        public CordisConfig build() {
            return new CordisConfig(this);
        }
    }
}
